# Generated by Django 3.1.4 on 2020-12-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('nip', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=80)),
                ('tempatLahir', models.CharField(blank=True, max_length=80, null=True)),
                ('tanggalLahir', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daftarPegawai',
            },
        ),
        migrations.CreateModel(
            name='Stasiun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80)),
                ('alamat', models.CharField(max_length=80)),
                ('telepon', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('kepalaStasiun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qcData.pegawai')),
            ],
            options={
                'db_table': 'daftarStasiun',
            },
        ),
    ]
