# Generated by Django 3.1.4 on 2020-12-02 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcData', '0002_auto_20201202_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataStasiun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('tMax', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tMin', models.DecimalField(decimal_places=1, max_digits=3)),
                ('t', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tD', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rH', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tekananUdara', models.DecimalField(decimal_places=1, max_digits=5)),
                ('hujan', models.DecimalField(decimal_places=1, max_digits=3)),
                ('stasiun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qcData.stasiun')),
            ],
            options={
                'db_table': 'dataStasiun',
            },
        ),
        migrations.AddConstraint(
            model_name='datastasiun',
            constraint=models.UniqueConstraint(fields=('tanggal', 'stasiun'), name='unique_waktudantempat'),
        ),
    ]
