# Generated by Django 3.1.4 on 2020-12-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcData', '0003_auto_20201203_0634'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stasiun',
            constraint=models.CheckConstraint(check=models.Q(kepalaStasiun__exact='id'), name='Kepala Stasiun harus pegawai yang bekerja di stasiun'),
        ),
    ]
