# Generated by Django 3.1.4 on 2020-12-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcData', '0004_auto_20201203_2018'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stasiun',
            name='Kepala Stasiun harus pegawai yang bekerja di stasiun',
        ),
        migrations.AddConstraint(
            model_name='stasiun',
            constraint=models.CheckConstraint(check=models.Q(kepalaStasiun__exact='Pegawai.stasiunKerja'), name='Kepala Stasiun harus pegawai yang bekerja di stasiun'),
        ),
    ]
