# Generated by Django 3.1.4 on 2020-12-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcData', '0005_auto_20201203_2023'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stasiun',
            name='Kepala Stasiun harus pegawai yang bekerja di stasiun',
        ),
    ]
