# Generated by Django 3.1.4 on 2020-12-22 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcData', '0006_auto_20201203_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataStasiunBersih',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tMaxClean', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tMinClean', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tClean', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tDClean', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rHClean', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tekananUdaraClean', models.DecimalField(decimal_places=1, max_digits=5)),
                ('hujanClean', models.DecimalField(decimal_places=1, max_digits=3)),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='qcData.datastasiun')),
            ],
            options={
                'db_table': 'dataStasiunBersih',
            },
        ),
    ]
