# Generated by Django 3.1.4 on 2020-12-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcData', '0007_datastasiunbersih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastasiunbersih',
            name='hujanClean',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='datastasiunbersih',
            name='rHClean',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='datastasiunbersih',
            name='tClean',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='datastasiunbersih',
            name='tDClean',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='datastasiunbersih',
            name='tMaxClean',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='datastasiunbersih',
            name='tMinClean',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='datastasiunbersih',
            name='tekananUdaraClean',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
