# Generated by Django 3.1.4 on 2021-01-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcData', '0008_auto_20201223_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastasiunbersih',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qcData.datastasiun'),
        ),
    ]
